name: TodoList_iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-test:

    runs-on: macos-13

    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.0.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
    
    - name: Build and test
      run: xcodebuild -project TodoListApp/TodoListApp.xcodeproj -scheme "TodoListApp" -destination "platform=iOS Simulator,name=iPhone 14,OS=17.0.1" clean build

